import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Permiso from '../../app/Models/Permiso';

export default class extends BaseSeeder {
  public async run () {
    await Permiso.createMany([
    {
      url:'/usuario',
      metodo:'post'
    },
    {
      url:'/usuario',
      metodo:'get'
    },
    {
      url:'/usuario',
      metodo:'put'
    },
    {
      url:'/usuario',
      metodo:'delete'
    },
    {
      url:'/rol',
      metodo:'post'
    },
    {
      url:'/rol',
      metodo:'get'
    },
    {
      url:'/rol',
      metodo:'put'
    },
    {
      url:'/rol',
      metodo:'delete'
    },    
    {
      url:'/permiso',
      metodo:'post'
    },
    {
      url:'/permiso',
      metodo:'get'
    },
    {
      url:'/permiso',
      metodo:'put'
    },
    {
      url:'/permiso',
      metodo:'delete'
    },    
    {
      url:'/vuelo',
      metodo:'post'
    },
    {
      url:'/vuelo',
      metodo:'get'
    },
    {
      url:'/vuelo',
      metodo:'put'
    },
    {
      url:'/vuelo',
      metodo:'delete'
    },
    {
      url:'/guacal',
      metodo:'post'
    },
    {
      url:'/guacal',
      metodo:'get'
    },
    {
      url:'/guacal',
      metodo:'put'
    },
    {
      url:'/guacal',
      metodo:'delete'
    },
    {
      url:'/ruta',
      metodo:'post'
    },
    {
      url:'/ruta',
      metodo:'get'
    },
    {
      url:'/ruta',
      metodo:'put'
    },
    {
      url:'/ruta',
      metodo:'delete'
    },
    {
      url:'/mascota',
      metodo:'post'
    },
    {
      url:'/mascota',
      metodo:'get'
    },
    {
      url:'/mascota',
      metodo:'put'
    },
    {
      url:'/mascota',
      metodo:'delete'
    },
    ])
  }
}
