import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import PermisoRol from '../../app/Models/PermisoRol';

export default class extends BaseSeeder {
  public async run () {
    await PermisoRol.createMany([
      /* SuperAdmin */
      {
        id_rol:1,
        id_permiso:1
      },
      {
        id_rol:1,
        id_permiso:2
      },
      {
        id_rol:1,
        id_permiso:3
      },
      {
        id_rol:1,
        id_permiso:4
      },
      {
        id_rol:1,
        id_permiso:5
      },
      {
        id_rol:1,
        id_permiso:6
      },
      {
        id_rol:1,
        id_permiso:7
      },
      {
        id_rol:1,
        id_permiso:8
      },
      {
        id_rol:1,
        id_permiso:9
      },
      {
        id_rol:1,
        id_permiso:10
      },
      {
        id_rol:1,
        id_permiso:11
      },
      {
        id_rol:1,
        id_permiso:12
      },
      {
        id_rol:1,
        id_permiso:13
      },
      {
        id_rol:1,
        id_permiso:14
      },
      {
        id_rol:1,
        id_permiso:15
      },
      {
        id_rol:1,
        id_permiso:16
      },
      {
        id_rol:1,
        id_permiso:17
      },
      {
        id_rol:1,
        id_permiso:18
      },
      {
        id_rol:1,
        id_permiso:19
      },
      {
        id_rol:1,
        id_permiso:20
      },
      {
        id_rol:1,
        id_permiso:21
      },
      {
        id_rol:1,
        id_permiso:22
      },
      {
        id_rol:1,
        id_permiso:23
      },
      {
        id_rol:1,
        id_permiso:24
      },
      {
        id_rol:1,
        id_permiso:25
      },
      {
        id_rol:1,
        id_permiso:26
      },
      {
        id_rol:1,
        id_permiso:27
      },
      {
        id_rol:1,
        id_permiso:28
      },
      {
        id_rol:1,
        id_permiso:29
      },
      {
        id_rol:1,
        id_permiso:30
      },
      {
        id_rol:1,
        id_permiso:31
      },
      {
        id_rol:1,
        id_permiso:32
      },
      {
        id_rol:1,
        id_permiso:33
      },
      {
        id_rol:1,
        id_permiso:34
      },
      {
        id_rol:1,
        id_permiso:35
      },
      {
        id_rol:1,
        id_permiso:36
      },
      {
        id_rol:1,
        id_permiso:37
      },
      {
        id_rol:1,
        id_permiso:38
      },
      {
        id_rol:1,
        id_permiso:39
      },
      {
        id_rol:1,
        id_permiso:40
      },
      {
        id_rol:1,
        id_permiso:41
      },
      {
        id_rol:1,
        id_permiso:42
      },
      {
        id_rol:1,
        id_permiso:43
      },
      {
        id_rol:1,
        id_permiso:44
      },
      {
        id_rol:1,
        id_permiso:45
      },
      {
        id_rol:1,
        id_permiso:46
      },
      {
        id_rol:1,
        id_permiso:47
      },
      {
        id_rol:1,
        id_permiso:48
      },
      {
        id_rol:1,
        id_permiso:49
      },
      {
        id_rol:1,
        id_permiso:50
      },
      /* Operador de Aerolinea */
      {
        id_rol:2,
        id_permiso:1
      },
      {
        id_rol:2,
        id_permiso:2
      },
      {
        id_rol:2,
        id_permiso:3
      },
      {
        id_rol:2,
        id_permiso:4
      },
      {
        id_rol:2,
        id_permiso:5
      },
      {
        id_rol:2,
        id_permiso:6
      },
      {
        id_rol:2,
        id_permiso:7
      },
      {
        id_rol:2,
        id_permiso:8
      },
      {
        id_rol:2,
        id_permiso:9
      },
      {
        id_rol:2,
        id_permiso:10
      },
      {
        id_rol:2,
        id_permiso:12
      },
      {
        id_rol:2,
        id_permiso:13
      },
      {
        id_rol:2,
        id_permiso:26
      },
      {
        id_rol:2,
        id_permiso:27
      },
      {
        id_rol:2,
        id_permiso:28
      },
      {
        id_rol:2,
        id_permiso:29
      },
      {
        id_rol:2,
        id_permiso:30
      },
      {
        id_rol:2,
        id_permiso:32
      },
      {
        id_rol:2,
        id_permiso:33
      },
      {
        id_rol:2,
        id_permiso:36
      },
      {
        id_rol:2,
        id_permiso:37
      },
      {
        id_rol:2,
        id_permiso:38
      },
      {
        id_rol:2,
        id_permiso:39
      },
      {
        id_rol:2,
        id_permiso:40
      },
      {
        id_rol:2,
        id_permiso:41
      },
      {
        id_rol:2,
        id_permiso:42
      },
      {
        id_rol:2,
        id_permiso:43
      },
      {
        id_rol:2,
        id_permiso:44
      },
      {
        id_rol:2,
        id_permiso:45
      },
      {
        id_rol:2,
        id_permiso:47
      },
      {
        id_rol:2,
        id_permiso:48
      },
      /* Usuario Registrado */
      {
        id_rol:3,
        id_permiso:2
      },
      {
        id_rol:3,
        id_permiso:3
      },
      {
        id_rol:3,
        id_permiso:7
      },
      {
        id_rol:3,
        id_permiso:8
      },
      {
        id_rol:3,
        id_permiso:11
      },
      {
        id_rol:3,
        id_permiso:12
      },
      {
        id_rol:3,
        id_permiso:13
      },
      {
        id_rol:3,
        id_permiso:14
      },
      {
        id_rol:3,
        id_permiso:15
      },
      {
        id_rol:3,
        id_permiso:27
      },
      {
        id_rol:3,
        id_permiso:28
      },
      {
        id_rol:3,
        id_permiso:31
      },
      {
        id_rol:3,
        id_permiso:32
      },
      {
        id_rol:3,
        id_permiso:33
      },
      {
        id_rol:3,
        id_permiso:34
      },
      {
        id_rol:3,
        id_permiso:35
      },
      {
        id_rol:3,
        id_permiso:37
      },
      {
        id_rol:3,
        id_permiso:38
      },
      {
        id_rol:3,
        id_permiso:42
      },
      {
        id_rol:3,
        id_permiso:43
      },
      {
        id_rol:3,
        id_permiso:46
      },
      {
        id_rol:3,
        id_permiso:47
      },
      {
        id_rol:3,
        id_permiso:48
      },
      {
        id_rol:3,
        id_permiso:49
      },
      {
        id_rol:3,
        id_permiso:50
      },
      /* Invitado */
      {
        id_rol:4,
        id_permiso:2
      },
      {
        id_rol:4,
        id_permiso:3
      },
      {
        id_rol:4,
        id_permiso:7
      },
      {
        id_rol:4,
        id_permiso:8
      },
      {
        id_rol:4,
        id_permiso:27
      },
      {
        id_rol:4,
        id_permiso:28
      },
      {
        id_rol:4,
        id_permiso:37
      },
      {
        id_rol:4,
        id_permiso:38
      },
      {
        id_rol:4,
        id_permiso:42
      },
      {
        id_rol:4,
        id_permiso:43
      },

    ])
  }
}
